#ifndef TDO_ERROR_H
#define TDO_ERROR_H

enum TdoError {
    TDO_ERROR_OK = 0,
    TDO_ERROR_UNKNOWN = -1,
    TDO_ERROR_ARG_FIRST = 1,
    TDO_ERROR_ARG_PARSE = 2,
    TDO_ERROR_MEMORY = 3,
    TDO_ERROR_FILE = 4,
    TDO_ERROR_INPUT = 5,
    TDO_ERROR_EOF = 6,
    TDO_ERROR_PIPE = 7,
    TDO_ERROR_NEWLINE = 8,
    TDO_ERROR_NEGATIVE = 9,
    TDO_ERROR_NUMBER = 10,
    TDO_ERROR_PREFIX = 11,
    TDO_ERROR_WOULD_BLOCK = 12,
};

#endif
